language: java
jdk: openjdk11
sudo: required

cache:
  directories:
    - $HOME/.m2

services:
  - mysql

before_script:
  - sudo cp $TRAVIS_BUILD_DIR/mysql.cnf /etc/mysql/conf.d/
  - sudo service mysql restart
  - export TZ=Europe/Minsk
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bestlunch;'
