language: java
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2
    -

services:
  - mysql

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS bestlunch DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'
